name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.5'
          architecture: 'x64'  # Explicit architecture
          cache: 'pip'
      
      - name: Install dependencies
        shell: cmd  # Explicit Windows shell
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -Ur requirements.txt
          pip install --no-cache-dir pyinstaller
      
      - name: Build executables
        shell: cmd
        run: |
          set PYTHONOPTIMIZE=2
          set PATH=%PATH%;%SystemRoot%\System32
          PyInstaller --clean BetterKnobVolumeMixer.spec
          PyInstaller --clean hotkeyfinder.spec
      
      - name: Prepare release
        shell: cmd
        run: |
          mkdir release
          copy dist\BetterKnobVolumeMixer.exe release\
          copy dist\hotkeyfinder.exe release\
          copy config.ini release\
      
      - name: Create ZIP
        run: Compress-Archive -Path release\* -DestinationPath dist/betterknob_windows_x86_64.zip
      
      - uses: actions/upload-artifact@v4
        with:
          name: betterknob_windows_x86_64
          path: dist/betterknob_windows_x86_64.zip

  publish:
    needs: [windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          draft: true
          prerelease: false
          files: |
            betterknob_windows_x86_64/*
